tasks:
  - init: |
      docker run -d --name rstudio -p 8787:8787 -e DISABLE_AUTH=true rocker/tidyverse:4.2.3
      sleep 20  # Wait to ensure container is up

      docker exec rstudio Rscript -e "install.packages(c('remotes', 'BiocManager'), repos='https://cloud.r-project.org')"

      # Install CRAN packages with version control
      docker exec rstudio Rscript -e "pkgs <- c(
        'httr=1.4.7', 'jsonlite=1.8.8', 'yaml=2.3.10', 'progress=1.2.3',
        'lattice=0.21.8', 'plyr=1.8.9',
        'XML=3.99-0.16', 'scales=1.3.0', 
        'data.table=1.16.0','hms=1.1.3',
        'rmarkdown=2.28', 'gtable=0.3.5',
        'dplyr=1.1.4', 'Rcpp=1.0.13',
        'png=0.1-8', 'dbplyr=2.3.4'
      );
      for (p in pkgs) {
        parts <- strsplit(p, '=')[[1]];
        remotes::install_version(parts[1], version = parts[2], repos='https://cloud.r-project.org')
      }"
      # Install GitHub packages (custom versions)
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/TwoSampleMR@0.6.16')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/MRInstruments@0.3.2')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/ieugwasr@1.0.4')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/gwasglue')"

ports:
  - port: 8787
    onOpen: open-browser
