image:

  file: gitpod/Dockerfile



ports:
  - port: 8787
    onOpen: open-preview
tasks:
  - init: echo "RStudio Server starting..."
    command: |
      sudo rstudio-server start
vscode:
  extensions:
