image:
  file: gitpod/.gitpod.Dockerfile

tasks:
  - name: Start RStudio
    init: |
      echo "Installing R packages..."
      Rscript .gitpod_init.R
    command: |
      echo "Starting RStudio server..."
      rserver --www-port=3000 --auth-none=1

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
