tasks:
  - init: |
      docker run -d --name rstudio -p 8787:8787 -e DISABLE_AUTH=true rocker/tidyverse:4.2.3
      sleep 20  # Wait to ensure container is up

      docker exec rstudio Rscript -e "install.packages(c('remotes', 'BiocManager'), repos='https://cloud.r-project.org')"

      # Install CRAN packages with version control
      docker exec rstudio Rscript -e "pkgs <- c(
        'httr=1.4.7', 'bit64=4.0.5', 'jsonlite=1.8.8', 'yaml=2.3.10', 'progress=1.2.3',
        'pillar=1.9.0', 'RSQLite=2.3.7', 'lattice=0.21.8', 'glue=1.7.0', 'digest=0.6.37',
        'colorspace=2.1.1', 'htmltools=0.5.8.1', 'Matrix=1.5.4.1', 'plyr=1.8.9',
        'XML=3.99-0.16', 'pkgconfig=2.0.3', 'scales=1.3.0', 'tibble=3.2.1', 'generics=0.1.3',
        'farver=2.1.2', 'cachem=1.1.0', 'withr=3.0.1', 'cli=3.6.3', 'magrittr=2.0.3',
        'crayon=1.5.3', 'memoise=2.0.1', 'evaluate=0.24.0', 'fansi=1.0.6', 'xml2=1.3.6',
        'data.table=1.16.0', 'prettyunits=1.2.0', 'hms=1.1.3', 'lifecycle=1.0.4',
        'matrixStats=1.3.0', 'stringr=1.5.1', 'munsell=0.5.1', 'rlang=1.1.4',
        'RCurl=1.98-1.13', 'rstudioapi=0.16.0', 'rjson=0.2.21', 'rappdirs=0.3.3',
        'labeling=0.4.3', 'rmarkdown=2.28', 'gtable=0.3.5', 'codetools=0.2-19',
        'curl=5.2.2', 'DBI=1.2.3', 'R6=2.5.1', 'knitr=1.48', 'dplyr=1.1.4', 'fastmap=1.2.0',
        'bit=4.0.5', 'utf8=1.2.4', 'filelock=1.0.3', 'stringi=1.8.4', 'Rcpp=1.0.13',
        'vctrs=0.6.5', 'png=0.1-8', 'dbplyr=2.3.4', 'tidyselect=1.2.1', 'xfun=0.47'
      );
      for (p in pkgs) {
        parts <- strsplit(p, '=')[[1]];
        remotes::install_version(parts[1], version = parts[2], repos='https://cloud.r-project.org')
      }"

      # Install Bioconductor packages (specific versions)
      docker exec rstudio Rscript -e "BiocManager::install(c(
        'MatrixGenerics', 'Biobase', 'gwasvcf', 'BiocFileCache', 'BSgenome',
        'GenomeInfoDbData', 'Rsamtools', 'GenomicRanges', 'XVector', 'BiocParallel',
        'KEGGREST', 'IRanges', 'GenomicFeatures', 'BiocGenerics', 'AnnotationDbi',
        'Biostrings', 'GenomeInfoDb', 'BiocIO', 'DelayedArray', 'GenomicAlignments',
        'rtracklayer', 'VariantAnnotation', 'restfulr', 'biomaRt'
      ), version='3.16', ask=FALSE)"

      # Install GitHub packages (custom versions)
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/MRInstruments@0.3.2')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/ieugwasr@1.0.4')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/TwoSampleMR@0.6.16')"
      docker exec rstudio Rscript -e "remotes::install_github('MRCIEU/gwasglue')"

ports:
  - port: 8787
    onOpen: open-browser
