image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo service rstudio-server start
      echo "RStudio server started"
  - command: sleep infinity

ports:
  - port: 8787
    onOpen: open-preview
