image:
  file: gitpod/.gitpod.Dockerfile

ports:
  - port: 8787
    onOpen: open-browser

tasks:
  - init: |
      echo "RStudio will be available at port 8787"
  - command: |
      # Start RStudio server (disable auth, default user is 'rstudio')
      rserver --www-port 8787 --auth-none=1
