image:
  file: Dockerfile

tasks:
  - name: Start RStudio
    init: echo "Gitpod environment initializing..."
    command: |
      echo "Visit the RStudio tab once the container is ready."

ports:
  - port: 8787
    onOpen: open-preview

vscode:
  extensions:
    - RDebugger.r-debugger
